---
galaxy_info:
  author: "Sergii Kotenko"
  description: sample rsyslog role
  license: GPLv2
  min_ansible_version: '2.4'
  platforms:
  - name: CentOS
    versions:
    - 7
  galaxy_tags:
  - rsyslog
dependencies: []
